### ISSUE TITLE
Improvement to new CI Process

### ISSUE THREAD

**Issue by mjp41** [microsoft/verona#198] opened 2020-07-21 11:56 UTC
- [x] Enable more types of cached build, e.g. RelWithDbgInfo (https://github.com/microsoft/verona/pull/197#discussion_r457989495)
- [x] Expose more flags automatically (https://github.com/microsoft/verona/pull/197#discussion_r457989949)
- [x] Fix Mac CI to not use hardcoded 4 parallism
- [x] Automatically determine `-j` option for ctest and pass as part of the test target.
- [x] Add CI pipelines to check that building LLVM directly works (not currently tested).
- [x] Add quiet option to the not print the subtasks in details.
- [x] `compile_commands.json` doesn't get generated any more
- [x] LLVM downloads always happen again (even though file is still there) -> `URL_HASH` not set
- [x] C++ standard reverted to C++11
- [x] Failed to compile LLVM with `-DVERONA_DOWNLOAD_LLVM=Off` on Linux Arch
- [x] Cannot use `GOOD_COMMIT` flag with CI/Nightly builds and get a different LLVM build
- [x] `-DEXTRA_VERONA_CMAKE_FLAGS=` doesn't seem to work
- [x] `-DCMAKE_BUILD_TYPE=Debug` doesn't propagate to Verona
- [x] Multiple builds per invocation of `ninja` on Linux, always building from scratch when passing compiler flags
- [x] If LLVM archive is not available (new hash, etc) the failure is cryptic: add an error message to that
- [x] Both `interpreter` and `compiler` were left out of the build, building only on `make check` (#265)

**Comment by rengolin** [comment] 2020-07-21 15:58
- [ ] `compile_commands.json` don't get generated any more
- [ ] Removing `CMakeCache.txt` and running CMake again makes `ninja` download LLVM again (even though it's still there)

**Comment by rengolin** [comment] 2020-07-21 16:06
Build with existing LLVM also doesn't work:
```
verona/build$ rm -rf *; cmake .. -G Ninja -DVERONA_LLVM_LOCATION=../external/llvm-project/install/
-- The CXX compiler identification is GNU 10.1.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Version: 6.2.0
-- Build type: 
-- CXX_STANDARD: 11
...
-- Setting LLVM_DIR as ../external/llvm-project/install//lib/cmake/llvm
-- Setting MLIR_DIR as ../external/llvm-project/install//lib/cmake/mlir
-- Setting LLVM_EXTERNAL_LIT as ../external/llvm-project/install//bin/llvm-lit
CMake Error at src/mlir/CMakeLists.txt:21 (find_package):
  Could not find a package configuration file provided by "MLIR" with any of
  the following names:

    MLIRConfig.cmake
    mlir-config.cmake
...
verona/build$ ls ../external/llvm-project/install//lib/cmake/mlir
AddMLIR.cmake  MLIRConfig.cmake  MLIRTargets.cmake  MLIRTargets-release.cmake
```

**Comment by rengolin** [comment] 2020-07-21 16:30
Ignore my last comment, the problem was full path vs relative path.

**Comment by rengolin** [comment] 2020-07-21 16:45
I'm also still experiencing problems when compiling LLVM directly, as reported [here](https://github.com/microsoft/verona/pull/197#issuecomment-661783171). Clean build dir, same error.

**Comment by sylvanc** [comment] 2020-07-23 14:34
```
$ cmake -GNinja .. ; ninja check

CMake Error at mlir-release-stamp/extract-mlir-release.cmake:51 (file):
  file RENAME failed to rename

 

    /home/sylvanc/dev/verona/build/mlir-release-prefix/src/ex-mlir-release1234/build

 

  to

 

    /home/sylvanc/dev/verona/build/mlir-release-prefix/src/mlir-release

 

  because: Permission denied

 

 

FAILED: mlir-release-prefix/src/mlir-release-stamp/mlir-release-download
cd /home/sylvanc/dev/verona/build/mlir-release-prefix/src && /opt/cmake-3.17.2-Linux-x86_64/bin/cmake -P /home/sylvanc/dev/verona/build/mlir-release-prefix/src/mlir-release-stamp/download-mlir-release.cmake && /opt/cmake-3.17.2-Linux-x86_64/bin/cmake -P /home/sylvanc/dev/verona/build/mlir-release-prefix/src/mlir-release-stamp/verify-mlir-release.cmake && /opt/cmake-3.17.2-Linux-x86_64/bin/cmake -P /home/sylvanc/dev/verona/build/mlir-release-prefix/src/mlir-release-stamp/extract-mlir-release.cmake && /opt/cmake-3.17.2-Linux-x86_64/bin/cmake -E touch /home/sylvanc/dev/verona/build/mlir-release-prefix/src/mlir-release-stamp/mlir-release-download
ninja: build stopped: subcommand failed.
```

**Comment by rengolin** [comment] 2020-08-03 09:56
The reason why the LLVM archive keeps downloading every time is because `URL_HASH` isn't being defined. We don't define the hash because the files are different, and the downloads can be considerable (for example, Debug Linux is a multi-GB file).

The only alternative I can imagine is for us to generate a `verona-llvm-install......hash` file for each archive in the `LLVM Build` CI job, and the Verona CMake file downloads that first, puts into a variable, and then set the `URL_HASH` as that variable.

**Comment by rengolin** [comment] 2020-08-03 15:20
@mjp41, @theodus: With #223 the development process goes back close to the state it was before adding `ExternalProject` to CMake. The other issues are less urgent and can take longer to happen.

@sylvanc, do you still have the `permission denied` problem? I have never seen that, and it's weird that the error is in the generated CMake files (`mlir-release-stamp/extract-mlir-release.cmake`) not in any that we created.

**Comment by rengolin** [comment] 2020-08-04 12:18
```
$ cmake .. -G Ninja -DEXTRA_VERONA_CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/clang++;-DCMAKE_C_COMPILER=/usr/bin/clang"
-- Down task for debug
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    EXTRA_VERONA_CMAKE_FLAGS

-- Build files have been written to: verona/build
```

Then...
```
$ ninja
...
-- The CXX compiler identification is GNU 10.1.0
-- The C compiler identification is GNU 10.1.0
```

**Comment by rengolin** [comment] 2020-08-04 12:22
Cannot build a debug build of Verona

```
$ cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
...
$ ninja
...
$ grep CMAKE_BUILD_TYPE verona-prefix/src/verona-build/CMakeCache.txt
CMAKE_BUILD_TYPE:STRING=
```

**Comment by mjp41** [comment] 2020-08-04 12:28
> Cannot build Verona with clang any more, or pass any options to it
> 
> ```
> $ cmake .. -G Ninja -DEXTRA_VERONA_CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/clang++;-DCMAKE_C_COMPILER=/usr/bin/clang"
> -- Down task for debug
> -- Configuring done
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     EXTRA_VERONA_CMAKE_FLAGS
> 
> -- Build files have been written to: verona/build
> ```
> 
> Then...
> 
> ```
> $ ninja
> ...
> -- The CXX compiler identification is GNU 10.1.0
> -- The C compiler identification is GNU 10.1.0
> ```

Do you have `-DVERONA_LLVM_LOCATION` set?

**Comment by rengolin** [comment] 2020-08-04 12:30
No, I'm using the download file for all builds.

**Comment by mjp41** [comment] 2020-08-04 13:16
It is `VERONA_EXTRA_CMAKE_ARGS`

**Comment by mjp41** [comment] 2020-08-04 13:20
@rengolin  I think Sylvan's issue was fixed by a reboot fixing permissions inside WSL.

**Comment by rengolin** [comment] 2020-08-04 13:58
> It is `VERONA_EXTRA_CMAKE_ARGS`

Hmm, then we need to update the [docs](https://github.com/microsoft/verona/blob/master/docs/building.md#build-instructions).

**Comment by rengolin** [comment] 2020-08-04 14:12
> @rengolin I think Sylvan's issue was fixed by a reboot fixing permissions inside WSL.

How hard would it be to add WSL to the CI? I think the Microsoft-hosted Windows machines support "bash" via WSL...

**Comment by mjp41** [comment] 2020-08-06 13:05
> Cannot use GOOD_COMMIT flag with CI/Nightly builds and get a different LLVM build

@rengolin Why do you want this?  Just update the submodule?  Then you don't have to do anything in the CI web interface.

**Comment by rengolin** [comment] 2020-08-06 14:50
This is so we can test different LLVM commits with Verona without having to commit and revert the submodule change, but I guess that's not really important. I mean, changing the commit is easy enough and we can do that on the upstream repo in a branch and test that.

Also, with the new CMake magic, we'd need to pass a new CMake variable along, etc etc. Not worthy. I'll remove the `GOOD_COMMIT` variable form the build and rely exclusively on the submodule hash.

**Comment by rengolin** [comment] 2020-08-10 11:44
Trying to build Verona on my work machine, build directory clean, using fresh checkout with the new changes (#235), I get these warnings in the Verona CMake step:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ERROR_DEPRECATED
    CMAKE_SUPPRESS_DEVELOPER_ERRORS
```

Doesn't break anything, but other users may think it's a bug and report it. Perhaps they need to be added to the list to avoid copying.

**Comment by rengolin** [comment] 2020-08-10 11:51
The `verona` target seems to be `phony` and triggers a full build every time, twice.

This is my CMake line:
```
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```

Then Ninja does:
```
$ ninja
[0/8] Performing build step for 'external'
ninja: no work to do.
[4/8] Performing configure step for 'verona'
-- Download LLVM: ON
-- Generating clangformat target using /bin/clang-format-9
-- Build Type for Verona Debug
-- Build types Release;Debug;RelWithDebInfo
-- Version: 6.2.0
-- Build type: Debug
-- CXX_STANDARD: 17
-- Required features: cxx_variadic_templates
-- Setting LLVM_DIR as /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/llvm
-- Setting MLIR_DIR as /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/mlir
-- Setting LLVM_EXTERNAL_LIT as /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/bin/llvm-lit
-- Using MLIRConfig.cmake in: /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/mlir
-- Using LLVMConfig.cmake in: /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/llvm
-- Building with -fPIC
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rengolin/devel/msrc/verona/build/verona-prefix/src/verona-build
[5/8] Performing build step for 'verona'
[93/93] Linking CXX executable src/compiler/veronac-sys
[6/8] Performing install step for 'verona'
[90/91] Install the project...
-- Install configuration: "Debug"
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./verona-ast
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./grammar.peg
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./veronac
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./veronac-sys
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./interpreter
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./interpreter-sys
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/stdlib/builtin.verona
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./verona-mlir
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/lib/libMLIRVerona.a
[8/8] Completed 'verona'
$ ninja check
[0/8] Performing build step for 'external'
ninja: no work to do.
[4/8] Performing configure step for 'verona'
-- Download LLVM: ON
-- Generating clangformat target using /bin/clang-format-9
-- Build Type for Verona Debug
-- Build types Release;Debug;RelWithDebInfo
-- Version: 6.2.0
-- Build type: Debug
-- CXX_STANDARD: 17
-- Required features: cxx_variadic_templates
-- Setting LLVM_DIR as /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/llvm
-- Setting MLIR_DIR as /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/mlir
-- Setting LLVM_EXTERNAL_LIT as /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/bin/llvm-lit
-- Using MLIRConfig.cmake in: /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/mlir
-- Using LLVMConfig.cmake in: /home/rengolin/devel/msrc/verona/build/Debug/mlir/install/lib/cmake/llvm
-- Building with -fPIC
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rengolin/devel/msrc/verona/build/verona-prefix/src/verona-build
[5/8] Performing build step for 'verona'
[90/90] Linking CXX executable bin/verona-mlir
[6/8] Performing install step for 'verona'
[90/91] Install the project...
-- Install configuration: "Debug"
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./verona-ast
-- Up-to-date: /home/rengolin/devel/msrc/verona/build/dist/./grammar.peg
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./veronac
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./veronac-sys
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./interpreter
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./interpreter-sys
-- Up-to-date: /home/rengolin/devel/msrc/verona/build/dist/stdlib/builtin.verona
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/./verona-mlir
-- Installing: /home/rengolin/devel/msrc/verona/build/dist/lib/libMLIRVerona.a
[7/8] Performing test step for 'verona'
Test project /home/rengolin/devel/msrc/verona/build/verona-prefix/src/verona-build
      Start  1: codegen/compile-fail/main-bad-return-type
      Start  2: codegen/compile-fail/main-class-has-generics
      Start  3: codegen/compile-fail/main-class-missing
```

Could this be related to the multiple build types that on Linux are not the same as on Windows?

**Comment by rengolin** [comment] 2020-08-10 12:02
Turns out, if I omit `-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++` from the CMake command line, it works, so it's not the build type, but the compiler override.

**Comment by rengolin** [comment] 2020-09-03 08:47
If the archive doesn't exist on the server, for example if you're changing the hash value, you get this cryptic error:
```
-- Detected GIT commit: b21ddded8f0
CMake Error at CMakeLists.txt:46 (string):
  string sub-command STRIP requires two arguments.
```

It would be nice if we had an error message checking that the file actually downloaded, but since this is a parameter of the external project itself, we may have to create a second gimmick to check it first.

**Comment by mjp41** [comment] 2020-09-03 09:00
> If the archive doesn't exist on the server, for example if you're changing the hash value, you get this cryptic error:
> 
> ```
> -- Detected GIT commit: b21ddded8f0
> CMake Error at CMakeLists.txt:46 (string):
>   string sub-command STRIP requires two arguments.
> ```
> 
> It would be nice if we had an error message checking that the file actually downloaded, but since this is a parameter of the external project itself, we may have to create a second gimmick to check it first.

I agree. I think it is fairly straightforward. I had this issue when one of the team failed to use submodules correctly, and it fails in this way.

**Comment by rengolin** [comment] 2020-11-03 10:26
I have confirmed the LLVM direct build is working fine (even on Arch Linux), so checking that box.

Also, the two remaining issues (rel-with-dgb and LLVM build) have not made a difference on our CI or quality, so I guess we can close this issue and we can reopen later if it breaks something.

**Closed by rengolin** 2020-11-03 10:26 UTC
